In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import pandas as pd
import numpy as np

# About Me

Sheng (Matthew) Lin:
* Joined Baruch Community in July, 2016, with a Bachelor degree in Financial Mathematics. 
* Worked as an Qunatitative Reserach at QuantPort, Jefferies for about two and half years. 
* Daily job is to generate alpha signals using various data set in equity market. 
* Will join Schonfeld Next week.

# Schedule:

* One and half and hour to go through basic pandas functionalities.
* Half an hour for of a small project, which is replicating a graph in a paper
* Q & A s
* Please free to interrupt me when you have questions
* I will try to ask some questions to make the class more interactive. 

# History and Relationship with Numpy

From WikiPedia:

The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.[3] 

Developer Wes McKinney started working on pandas in 2008 while at AQR Capital Management out of the need for a high performance, flexible tool to perform quantitative analysis on financial data. Before leaving AQR he was able to convince management to allow him to open source the library.


This is a package designed for processing financial data, specifically time Series.

Recommand book:

Python for Data Analysis:

![alt text](python.jpg)

Why not Python for finance?

As you could see letter, Pandas was built on numpy.  Some functions could be used interchangable.

# Series and DataFrame

## Series

In [4]:
## create an seires without index
obj = pd.Series([1, 2, 3, 4])
obj

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
## compared to np.array
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [6]:
obj.values

array([1, 2, 3, 4])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

If you are familar with R, a way to think about relationship between pandas and numpy are like matrix and Data.Frame.

In [8]:
## series with index
obj2 = pd.Series([1, 2, 3, 4], index = ["c", "d", "e", "f"])

In [9]:
obj2

c    1
d    2
e    3
f    4
dtype: int64

In [10]:
obj2["c"]

1

In [11]:
obj2["d"] = 6

In [12]:
obj2[["c", "f", "e"]]

c    1
f    4
e    3
dtype: int64

One way to think about series is "sorted dictionary". Index can change the order of return series.

In [13]:
## bollean mask
obj2[obj2 >  2]

d    6
e    3
f    4
dtype: int64

In [14]:
obj2 > 2

c    False
d     True
e     True
f     True
dtype: bool

In [15]:
## numerical function
np.exp(obj2)

c      2.718282
d    403.428793
e     20.085537
f     54.598150
dtype: float64

In [16]:
## build sereis from dictionary
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
## override index
states = ["California", "Ohio", "Oregon", "Texas"]

In [22]:
obj4 = pd.Series(sdata, index = states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Note that Utah is excluded, and California has some nans.

In [25]:
## don't do this
obj4 == np.nan

California    False
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
## alignment of index, this could be dangerous
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj3.reset_index(drop = True)

0    35000
1    71000
2    16000
3     5000
dtype: int64

In [35]:
## watch out if you lose track of index
obj3.reset_index(drop = True) + obj3

0        NaN
1        NaN
2        NaN
3        NaN
Ohio     NaN
Oregon   NaN
Texas    NaN
Utah     NaN
dtype: float64

In [36]:
## change names
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

This seems to be not so useful if you only have one Series. It would be more useful if we have a dataframe.

In [37]:
obj

0    1
1    2
2    3
3    4
dtype: int64

In [38]:
obj.index = ["A", "B", "C", "D"]

In [39]:
obj

A    1
B    2
C    3
D    4
dtype: int64

In [40]:
## of course can apply some aritmematic funciton
obj.mean()

2.5

Let's continue to dataframe. Datafrmae could be considered as an ordered dictionary of Series. Even though it seems to be two dimensional, with multilevel index, it can be used to stored high-dimensional data.

## DataFrame

In [41]:
## generate datafrmae from dictionary

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [45]:
## first few crows
frame.head()  ## like head(data) in R, pandas is an OOP library

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [46]:
## arrange order for columns
pd.DataFrame(data, columns = ["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [113]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four','five', 'six'])

In [114]:
## additional columns
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [115]:
## assin series with index
val = pd.Series([- 1.2, - 1.5, - 1.7], index = ["two", "four", "five"])

In [116]:
frame2["debt"] = val

In [117]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [118]:
## withou index
val = pd.Series([- 1.2, - 1.5, - 1.7])
frame2["debt"] = val

In [119]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [120]:
## not using series
val  = [-1.2, -1.5, -1.7] 
frame2["debt"] = val

ValueError: Length of values does not match length of index

As We see, Sereis have some dictionary-like functionality.

In [121]:
## creating new column
frame2["eastern"] = frame2.state == "Ohio"
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [122]:
frame2.eastern  ## also work

one       True
two       True
three     True
four     False
five     False
six      False
Name: eastern, dtype: bool

In [123]:
## warnings
frame.west = frame2.state != "Ohio"

In [124]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [125]:
test_col = frame2["state"]

In [126]:
test_col["one"] = "New York"  ##intend to creat a copy

/home/matthew/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [127]:
## this is equialvent to, chain operation is not recommended
frame2["state"]["one"]

'New York'

In [128]:
## no warnings
frame2.loc["one", "state"] = "Ohio"

Recommand to read: 

https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas

The issue here is depending on your slicing scheme of pandas, it may return a view or a copy. When you try to assign value to a view, it also modifies the origional data. Try to avoid chain assignment as you can

In [129]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [130]:
test_col = frame2["state"].copy()
test_col["one"] = "New York"

In [131]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [132]:
## nested keys, outter as column name, inner as index
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [133]:
frame3 = pd.DataFrame(pop)

In [134]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [135]:
## transpose 
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [136]:
frame3.index.name = "year"

In [137]:
frame3.columns.name = "state"

In [138]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [139]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [141]:
## accomodate all values
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, nan, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, nan, False],
       [2002, 'Nevada', 2.9, nan, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

## Index object

In [142]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index

In [143]:
index

Index(['a', 'b', 'c'], dtype='object')

In [144]:
index[1:]

Index(['b', 'c'], dtype='object')

In [145]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [149]:
## can have duplicated index
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [150]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [151]:
"foo" in dup_labels

True

Index is immutable, safer to share between objects

### Essential functionalities

In [153]:
## reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [154]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [156]:
## directly reset index
obj.reset_index()

index    0
0     d  4.5
1     b  7.2
2     a -5.3
3     c  3.6

In [158]:
obj.reset_index(drop = True)

0    4.5
1    7.2
2   -5.3
3    3.6
dtype: float64

In [159]:
## reindexing to a new sereis
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Reindex avoid modifying index in-place.

In [160]:
## this is very useful for timeseries data. 
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

# Time Series

## Built-in datatime

strftime, strptime, datedifference, timezone convertion.

# Merging/ Conecting DataFrame

# Groupby

# Ploting

# Lambda function

# Numpy v.s Pandas

## Production Issues

# Conclusion